# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ukrina software
email: ukrinasoft@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ukrinasoft voor al uw software eisen. Wij helpen
  u graag om uw dagelijkse werkzaamheden
  met onze passie en kennis te assisteren.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ukrinasoftware.github.io" # the base hostname & protocol for your site
twitter_username: ukrinasoft
github_username:  ukrinasoft

# Build settings
markdown: kramdown
